services:
  - type: web
    name: prices-mcp
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11